/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import CustomPackage.UserInformation;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class UserProfile extends javax.swing.JFrame {
    private UserInformation userInformation;

    /**
     * Creates new form UserProfile
     */
    public UserProfile(UserInformation userInformation) {
        initComponents();
        this.userInformation = userInformation;
        userNamefield.setText(userInformation.getUserName());
        firstNamefield.setText(userInformation.getFirstName());
        userlastname.setText(userInformation.getLastName());
        emailfield.setText(userInformation.getEmail());
        phonefield.setText(userInformation.getPhone());
        addressfiled.setText(userInformation.getAddress());
        usernametop.setText(userInformation.getFirstName()+"'s Profile");
        
    }
    
    public  UserProfile(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNamefield = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNamefield = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userlastname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailfield = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phonefield = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        addressfiled = new javax.swing.JLabel();
        usernametop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        userNamefield.setText("jLabel2");

        jLabel2.setText("First Name");

        firstNamefield.setText("jLabel3");

        jLabel3.setText("Last Name");

        userlastname.setText("jlabel4");

        jLabel5.setText("Email");

        emailfield.setText("jlabel4");

        jLabel7.setText("Phone");

        phonefield.setText("jlabel4");

        Address.setText("Address");

        addressfiled.setText("jlabel4");

        usernametop.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        usernametop.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstNamefield))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(userNamefield)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailfield))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)
                                        .addComponent(Address))
                                    .addGap(75, 75, 75)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phonefield)
                                        .addComponent(userlastname)
                                        .addComponent(addressfiled))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(usernametop)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(usernametop)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNamefield))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNamefield))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userlastname))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailfield))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phonefield))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(addressfiled))
                .addContainerGap(317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
       
       
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               UserProfile userProfile =  new UserProfile();
               userProfile.setVisible(true);
               userProfile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel addressfiled;
    private javax.swing.JLabel emailfield;
    private javax.swing.JLabel firstNamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel phonefield;
    private javax.swing.JLabel userNamefield;
    private javax.swing.JLabel userlastname;
    private javax.swing.JLabel usernametop;
    // End of variables declaration//GEN-END:variables
}
