/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Flight;

import Admin.AdminInformation;
import Airlines.AirlinesInformation;
import Airport.AirportInformation;
import DatabaseHandaler.DatabaseHandler;
import Feeds.Feed;
import FlightTransitInformation.FlightTransit;
import Flightschedule.FlightSchedule;
import MyDate.MyDate;
import Root.RootInformation;
import SeatInformation.SeatInfo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddFlight extends javax.swing.JFrame {

    private AdminInformation adminInformation;
    DatabaseHandler databaseHandalr = new DatabaseHandler();
    private ArrayList<AirportInformation> airportlist;

    /**
     * Creates new form AddFlight
     */
    public AddFlight(AdminInformation adminInformation) {
        initComponents();
        this.adminInformation = adminInformation;

        Connection connection = databaseHandalr.connectDatabase();

        ResultSet resultset = databaseHandalr.getAirlines(connection);
        ArrayList<AirlinesInformation> airlinesList = databaseHandalr.getAirlinesInformation(resultset);
        // ArrayList<String> AirlinesNames = new ArrayList<>();

        for (AirlinesInformation airlinesInformation : airlinesList) {
            AIrlinesNameCombobox.addItem(airlinesInformation.getAirlinesName());
        }

        resultset = databaseHandalr.getAirportResultSet(connection);

        airportlist = databaseHandalr.getAirportInformationList(resultset);
        HashSet<String> airportCitySet = new HashSet<>();
        HashSet<String> airportNameSet = new HashSet<>();

        for (AirportInformation airportInformation : airportlist) {
            airportCitySet.add(airportInformation.getCityName());
            airportNameSet.add(airportInformation.getAirportName());
        }

        Iterator<String> it = airportCitySet.iterator();
        while (it.hasNext()) {
            String city = it.next();
            departurecityCOmbobox.addItem(city);
            destinationcitycombobox.addItem(city);

        }

        Iterator<String> it1 = airportNameSet.iterator();

        while (it1.hasNext()) {
            String airportName = it1.next();
            transit1combobox.addItem(airportName);
            transit2combobox.addItem(airportName);

        }

    }

    public AddFlight() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AIrlinesNameCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        flightNumberJtextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        destinationcitycombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        departurecityCOmbobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        departureAirportName = new javax.swing.JComboBox<>();
        destinationAirportName = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        businessclassseat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        economyclassseat = new javax.swing.JTextField();
        firstclassseat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        firstclassseatprice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        businessclassseatprice = new javax.swing.JTextField();
        economyclassseatprice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tuesday = new javax.swing.JCheckBox();
        tuearrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        tuespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        tuecombobox = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        thrusday = new javax.swing.JCheckBox();
        thrusarrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        thrusspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        thruscombobox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        satarday = new javax.swing.JCheckBox();
        satarivaltimejspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        satspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        satcombobox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        wednesday = new javax.swing.JCheckBox();
        wedarrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        wedspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        wedcombobox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        friday = new javax.swing.JCheckBox();
        frisspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        fricombobox = new javax.swing.JComboBox<>();
        friarrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        jPanel3 = new javax.swing.JPanel();
        sunday = new javax.swing.JCheckBox();
        sunarrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        sunspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        suncombobox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        monday = new javax.swing.JCheckBox();
        monarrivaltimespinner = new javax.swing.JSpinner(new SpinnerDateModel());
        monspinner = new javax.swing.JSpinner(new SpinnerDateModel());
        moncombobox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        transit2combobox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        transit1CityName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        transit2cityName = new javax.swing.JTextField();
        transit1combobox = new javax.swing.JComboBox<>();
        saveflightbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Information"));

        jLabel2.setText("Flight Number");

        AIrlinesNameCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIrlinesNameComboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Airlines Name");

        jLabel4.setText("Destination");

        destinationcitycombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                destinationcitycomboboxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Departure City");

        departurecityCOmbobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departurecityCOmboboxItemStateChanged(evt);
            }
        });
        departurecityCOmbobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departurecityCOmboboxActionPerformed(evt);
            }
        });

        jLabel8.setText("Airport Name");

        jLabel9.setText("Airport Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(departureAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(departurecityCOmbobox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(AIrlinesNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(flightNumberJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destinationcitycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destinationAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AIrlinesNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(flightNumberJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departurecityCOmbobox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(destinationcitycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(departureAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seat Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel5.setText("First Class");

        jLabel6.setText("Business Class");

        jLabel7.setText("Economy Class");

        jLabel15.setText("Ticket Price");

        jLabel16.setText("Ticket Price");

        jLabel17.setText("Ticket Price");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(46, 46, 46)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(firstclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(firstclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(businessclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(economyclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(businessclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(economyclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(firstclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(firstclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(businessclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(businessclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(economyclassseat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17)
                    .addComponent(economyclassseatprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("TIme"));

        tuesday.setText("Tuesday ");
        tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayActionPerformed(evt);
            }
        });

        JSpinner.DateEditor timeEditor4 = new JSpinner.DateEditor(tuearrivaltimespinner, "HH:mm:ss");
        tuearrivaltimespinner.setEditor(timeEditor4);
        tuearrivaltimespinner.setValue(new Date());

        JSpinner.DateEditor timeEditor18 = new JSpinner.DateEditor(tuespinner, "HH:mm:ss");
        tuespinner.setEditor(timeEditor18);
        tuespinner.setValue(new Date());

        tuecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tuesday)
                .addGap(26, 26, 26)
                .addComponent(tuespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(tuecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(tuearrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuesday)
                    .addComponent(tuespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuearrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        thrusday.setText("Thursday");

        JSpinner.DateEditor timeEditor6 = new JSpinner.DateEditor(thrusarrivaltimespinner, "HH:mm:ss");
        thrusarrivaltimespinner.setEditor(timeEditor6);
        thrusarrivaltimespinner.setValue(new Date());

        JSpinner.DateEditor timeEditor14 = new JSpinner.DateEditor(thrusspinner, "HH:mm:ss");
        thrusspinner.setEditor(timeEditor14);
        thrusspinner.setValue(new Date());

        thruscombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thrusday)
                .addGap(29, 29, 29)
                .addComponent(thrusspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(thruscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(thrusarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thrusday)
                    .addComponent(thrusspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thruscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thrusarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        satarday.setText("Satarday");

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(satarivaltimejspinner, "HH:mm:ss");
        satarivaltimejspinner.setEditor(timeEditor);
        satarivaltimejspinner.setValue(new Date());

        JSpinner.DateEditor timeEditor9 = new JSpinner.DateEditor(satspinner, "HH:mm:ss");
        satspinner.setEditor(timeEditor9);
        satspinner.setValue(new Date());

        satcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(satarday)
                .addGap(29, 29, 29)
                .addComponent(satspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(satcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(satarivaltimejspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satarday)
                    .addComponent(satspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satarivaltimejspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        wednesday.setText("Wednesday ");
        wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayActionPerformed(evt);
            }
        });

        JSpinner.DateEditor timeEditor5 = new JSpinner.DateEditor(wedarrivaltimespinner, "HH:mm:ss");
        wedarrivaltimespinner.setEditor(timeEditor5);
        wedarrivaltimespinner.setValue(new Date());

        JSpinner.DateEditor timeEditor16 = new JSpinner.DateEditor(wedspinner, "HH:mm:ss");
        wedspinner.setEditor(timeEditor16);
        wedspinner.setValue(new Date());

        wedcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wednesday)
                .addGap(18, 18, 18)
                .addComponent(wedspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(wedcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(wedarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesday)
                    .addComponent(wedspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wedcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wedarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        friday.setText("Friday ");

        JSpinner.DateEditor timeEditor17 = new JSpinner.DateEditor(frisspinner, "HH:mm:ss");
        frisspinner.setEditor(timeEditor17);
        frisspinner.setValue(new Date());

        fricombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        JSpinner.DateEditor timeEditor8 = new JSpinner.DateEditor(friarrivaltimespinner, "HH:mm:ss");
        friarrivaltimespinner.setEditor(timeEditor8);
        friarrivaltimespinner.setValue(new Date());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friday)
                .addGap(38, 38, 38)
                .addComponent(frisspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(fricombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(friarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friday)
                    .addComponent(frisspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fricombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sunday.setText("Sunday");
        sunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayActionPerformed(evt);
            }
        });

        JSpinner.DateEditor timeEditor1 = new JSpinner.DateEditor(sunarrivaltimespinner, "HH:mm:ss");
        sunarrivaltimespinner.setEditor(timeEditor1);
        sunarrivaltimespinner.setValue(new Date());

        JSpinner.DateEditor timeEditor11 = new JSpinner.DateEditor(sunspinner, "HH:mm:ss");
        sunspinner.setEditor(timeEditor11);
        sunspinner.setValue(new Date());

        suncombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sunday)
                .addGap(36, 36, 36)
                .addComponent(sunspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(suncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(sunarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sunday)
                    .addComponent(sunspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        monday.setText("Monday");

        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(monarrivaltimespinner, "HH:mm:ss");
        monarrivaltimespinner.setEditor(timeEditor2);
        monarrivaltimespinner.setValue(new Date());

        JSpinner.DateEditor timeEditor10 = new JSpinner.DateEditor(monspinner, "HH:mm:ss");
        monspinner.setEditor(timeEditor10);
        monspinner.setValue(new Date());

        moncombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday ", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monday)
                .addGap(33, 33, 33)
                .addComponent(monspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(moncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(monarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday)
                    .addComponent(monspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monarrivaltimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Transit Information"));

        jLabel11.setText("Transit 1");

        jLabel12.setText("Transit 2");

        transit2combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        transit2combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transit2comboboxItemStateChanged(evt);
            }
        });
        transit2combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transit2comboboxActionPerformed(evt);
            }
        });

        jLabel13.setText("City Name");

        transit1CityName.setEditable(false);

        jLabel14.setText("City Name");

        transit2cityName.setEditable(false);

        transit1combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        transit1combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transit1comboboxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(transit1combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transit2combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transit1CityName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(transit2cityName))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(transit1CityName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transit1combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transit2cityName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(transit2combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        saveflightbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveflightbutton.setText("Save this Flight");
        saveflightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveflightbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveflightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel10)
                        .addGap(57, 57, 57)
                        .addComponent(saveflightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayActionPerformed

    private void sundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayActionPerformed

    private void AIrlinesNameComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIrlinesNameComboboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_AIrlinesNameComboboxActionPerformed

    private void departurecityCOmboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departurecityCOmboboxItemStateChanged
        // TODO add your handling code here:
        departureAirportName.removeAllItems();
        Connection connection = databaseHandalr.connectDatabase();
        String selectedCity = departurecityCOmbobox.getSelectedItem().toString();

        ResultSet resultSet = databaseHandalr.getAirportResultSetByCityName(connection, selectedCity);
        ArrayList<AirportInformation> list = databaseHandalr.getAirportInformationList(resultSet);

        for (AirportInformation airportInformation : list) {
            departureAirportName.addItem(airportInformation.getAirportName());
        }


    }//GEN-LAST:event_departurecityCOmboboxItemStateChanged

    private void departurecityCOmboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departurecityCOmboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departurecityCOmboboxActionPerformed

    private void destinationcitycomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinationcitycomboboxItemStateChanged
        // TODO add your handling code here:
        destinationAirportName.removeAllItems();
        Connection connection = databaseHandalr.connectDatabase();
        String selectedCity = destinationcitycombobox.getSelectedItem().toString();

        ResultSet resultSet = databaseHandalr.getAirportResultSetByCityName(connection, selectedCity);
        ArrayList<AirportInformation> list = databaseHandalr.getAirportInformationList(resultSet);

        for (AirportInformation airportInformation : list) {
            destinationAirportName.addItem(airportInformation.getAirportName());
        }
    }//GEN-LAST:event_destinationcitycomboboxItemStateChanged

    private void transit2comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transit2comboboxItemStateChanged
        // TODO add your handling code here:
        Connection connection = databaseHandalr.connectDatabase();
        String airportName1 = transit2combobox.getSelectedItem().toString();

        ResultSet resultSet = databaseHandalr.getAirportResultSetByAirportName(connection, airportName1);
        ArrayList<AirportInformation> list1 = databaseHandalr.getAirportInformationList(resultSet);
        transit2cityName.setText(list1.get(0).getCityName());

    }//GEN-LAST:event_transit2comboboxItemStateChanged

    private void transit2comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transit2comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transit2comboboxActionPerformed

    private void transit1comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transit1comboboxItemStateChanged
        // TODO add your handling code here:

        String airportName = transit1combobox.getSelectedItem().toString();
        Connection connection = databaseHandalr.connectDatabase();
        ResultSet resultSet = databaseHandalr.getAirportResultSetByAirportName(connection, airportName);
        ArrayList<AirportInformation> list = databaseHandalr.getAirportInformationList(resultSet);
        transit1CityName.setText(list.get(0).getCityName());


    }//GEN-LAST:event_transit1comboboxItemStateChanged

    private void saveflightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveflightbuttonActionPerformed
        // TODO add your handling code here:

        String airlinesName = AIrlinesNameCombobox.getSelectedItem().toString();
        String flightNumber = flightNumberJtextField.getText().trim().toString();
        String departureAirportNames = departureAirportName.getSelectedItem().toString();
        String destinationAirportNames = destinationAirportName.getSelectedItem().toString();

        Connection connection = databaseHandalr.connectDatabase();
        ResultSet resultSet = databaseHandalr.getFlightInformationByFlightNumber(flightNumber, connection);
        ArrayList<FlightInformation> flightInformations = databaseHandalr.getFlightInformationList(resultSet);

        if (flightInformations.size() == 0) {

            ResultSet resultSet1 = databaseHandalr.getAirportResultSetByAirportName(connection, departureAirportNames);
            ArrayList<AirportInformation> departureAirportInformationlist = databaseHandalr.getAirportInformationList(resultSet1);

            ResultSet resultSet2 = databaseHandalr.getAirportResultSetByAirportName(connection, destinationAirportNames);
            ArrayList<AirportInformation> destinationAirportInformationList = databaseHandalr.getAirportInformationList(resultSet2);

            String departureAirportCode = departureAirportInformationlist.get(0).getAirportCode();
            String destinationAirportCode = destinationAirportInformationList.get(0).getAirportCode();

            ResultSet rootResultSet = databaseHandalr.getRootIdByAirportCode(departureAirportCode, destinationAirportCode, connection);
            ArrayList<RootInformation> root = databaseHandalr.getALlRootInformationList(rootResultSet);

            if (root.size() > 0) {
                int flightRootId = root.get(0).getRootId();

                ArrayList<FlightSchedule> flightScheduleList = new ArrayList<>();

                FlightSchedule flightSchedule = null;

                if (satarday.isSelected()) {
                    String[] value = satspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = satcombobox.getSelectedItem().toString();
                    String[] value1 = satarivaltimejspinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Satarday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }
                if (sunday.isSelected()) {
                    String[] value = sunspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = suncombobox.getSelectedItem().toString();
                    String[] value1 = sunarrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Sunday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }
                if (monday.isSelected()) {
                    String[] value = monspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = moncombobox.getSelectedItem().toString();
                    String[] value1 = monarrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Monday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }
                if (tuesday.isSelected()) {
                    String[] value = tuespinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = tuecombobox.getSelectedItem().toString();
                    String[] value1 = tuearrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Tuesday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }

                if (wednesday.isSelected()) {
                    String[] value = wedspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = wedcombobox.getSelectedItem().toString();
                    String[] value1 = wedarrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Wednesday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }

                if (thrusday.isSelected()) {
                    String[] value = thrusspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = thruscombobox.getSelectedItem().toString();
                    String[] value1 = thrusarrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Thrusday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }
                if (friday.isSelected()) {
                    String[] value = frisspinner.getValue().toString().split(" ");
                    String departureTime = value[3];
                    String ArivalDay = fricombobox.getSelectedItem().toString();
                    String[] value1 = friarrivaltimespinner.getValue().toString().split(" ");
                    String arivalTime = value1[3];
                    flightSchedule = new FlightSchedule("Friday", departureTime, ArivalDay, arivalTime);

                    flightScheduleList.add(flightSchedule);

                }
               for(FlightSchedule flightSchedule1:flightScheduleList){
                   flightSchedule.setFlightNumber(flightNumber);
               }

                int firstclassSeat = Integer.parseInt(firstclassseat.getText().trim().toString());
                int businessclassSeat = Integer.parseInt(businessclassseat.getText().trim().toString());
                int economyclassSeat = Integer.parseInt(economyclassseat.getText().trim().toString());

                int firstclassSeatPrice = Integer.parseInt(firstclassseatprice.getText().toString().trim());
                int businessclassSeatPrice = Integer.parseInt(businessclassseatprice.getText().toString().trim());
                int economyclassSeatPrice = Integer.parseInt(economyclassseatprice.getText().toString().trim());

                SeatInfo seatInfo = new SeatInfo(firstclassSeat, businessclassSeat, economyclassSeat,firstclassSeatPrice,businessclassSeatPrice,economyclassSeatPrice ,flightNumber);

                String transit1AirportName = null;
                String transit2AirportName = null;
                ResultSet resultSetfortransit;

                transit1AirportName = transit1combobox.getSelectedItem().toString();
                transit2AirportName = transit2combobox.getSelectedItem().toString();

                FlightTransit flightTransit;
                if (!transit1AirportName.equals("None") && !transit2AirportName.equals("None")) {

                    resultSetfortransit = databaseHandalr.getAirportResultSetByAirportName(connection, transit1AirportName);
                    ArrayList<AirportInformation> transit1airportlist = databaseHandalr.getAirportInformationList(resultSetfortransit);

                    resultSetfortransit = databaseHandalr.getAirportResultSetByAirportName(connection, transit2AirportName);
                    ArrayList<AirportInformation> transit2airportlist = databaseHandalr.getAirportInformationList(resultSetfortransit);

                    flightTransit = new FlightTransit(flightNumber, transit1airportlist.get(0).getAirportCode(), transit1airportlist.get(0).getAirportCode());

                } else if (!transit1AirportName.equals("None") && transit2AirportName.equals("None")) {
                    resultSetfortransit = databaseHandalr.getAirportResultSetByAirportName(connection, transit1AirportName);
                    ArrayList<AirportInformation> transit1airportlist = databaseHandalr.getAirportInformationList(resultSetfortransit);
                    flightTransit = new FlightTransit(flightNumber, transit1airportlist.get(0).getAirportCode(), null);
                } else if (transit1AirportName.equals("None") && !transit2AirportName.equals("None")) {

                    resultSetfortransit = databaseHandalr.getAirportResultSetByAirportName(connection, transit2AirportName);
                    ArrayList<AirportInformation> transit2airportlist = databaseHandalr.getAirportInformationList(resultSetfortransit);

                    flightTransit = new FlightTransit(flightNumber, null, transit2airportlist.get(0).getAirportCode());

                } else {
                    flightTransit = new FlightTransit(flightNumber, null, null);
                }

                ResultSet airlinesResultSet = databaseHandalr.getAirlinesByAirlinesName(airlinesName, connection);
                ArrayList<AirlinesInformation> airlinesList = databaseHandalr.getAirlinesInformation(airlinesResultSet);
                int airlinesid = airlinesList.get(0).getAirlinesId();

                FlightInformation flightInformation = new FlightInformation(airlinesid, flightNumber, flightRootId, adminInformation.getAdminId());
                int res = databaseHandalr.insertFlight(flightInformation, connection);

                if (res > 0) {
                   boolean isAllScheduleInserted = true;
                   for(FlightSchedule flightSchedule1 : flightScheduleList){
                       int check = databaseHandalr.insertFlightSchedule(flightSchedule, connection);
                       if(check==0){
                           isAllScheduleInserted = false;
                       }
                   }
                    int seatRes = databaseHandalr.insertSeatInfo(seatInfo, connection);
                    int transitres = databaseHandalr.insertTransit(flightTransit, connection);

                    if (isAllScheduleInserted && seatRes > 0 && transitres > 0) {
                        Feed feed = new Feed(adminInformation.getAdminId(), "Added a new Flight "+flightNumber, MyDate.getCurrentdate());
                        databaseHandalr.insertFeed(feed, connection);
                        JOptionPane.showMessageDialog(null, "this FLight is Inserted Successfully");
                    } else {
                        JOptionPane.showMessageDialog(null, "this FLight is not inserted ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "this FLight is Not Inserted ");
                }

            } else {
                JOptionPane.showMessageDialog(null, "this Root Is Not Available in the Database..Please Add This Root First");
            }

        } else {
            JOptionPane.showMessageDialog(null, "This Flight number is already added in the Database.Please Change The Flight Number..");
        }
    }//GEN-LAST:event_saveflightbuttonActionPerformed

    private void tuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AIrlinesNameCombobox;
    private javax.swing.JTextField businessclassseat;
    private javax.swing.JTextField businessclassseatprice;
    private javax.swing.JComboBox<String> departureAirportName;
    private javax.swing.JComboBox<String> departurecityCOmbobox;
    private javax.swing.JComboBox<String> destinationAirportName;
    private javax.swing.JComboBox<String> destinationcitycombobox;
    private javax.swing.JTextField economyclassseat;
    private javax.swing.JTextField economyclassseatprice;
    private javax.swing.JTextField firstclassseat;
    private javax.swing.JTextField firstclassseatprice;
    private javax.swing.JTextField flightNumberJtextField;
    private javax.swing.JSpinner friarrivaltimespinner;
    private javax.swing.JComboBox<String> fricombobox;
    private javax.swing.JCheckBox friday;
    private javax.swing.JSpinner frisspinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner monarrivaltimespinner;
    private javax.swing.JComboBox<String> moncombobox;
    private javax.swing.JCheckBox monday;
    private javax.swing.JSpinner monspinner;
    private javax.swing.JCheckBox satarday;
    private javax.swing.JSpinner satarivaltimejspinner;
    private javax.swing.JComboBox<String> satcombobox;
    private javax.swing.JSpinner satspinner;
    private javax.swing.JButton saveflightbutton;
    private javax.swing.JSpinner sunarrivaltimespinner;
    private javax.swing.JComboBox<String> suncombobox;
    private javax.swing.JCheckBox sunday;
    private javax.swing.JSpinner sunspinner;
    private javax.swing.JSpinner thrusarrivaltimespinner;
    private javax.swing.JComboBox<String> thruscombobox;
    private javax.swing.JCheckBox thrusday;
    private javax.swing.JSpinner thrusspinner;
    private javax.swing.JTextField transit1CityName;
    private javax.swing.JComboBox<String> transit1combobox;
    private javax.swing.JTextField transit2cityName;
    private javax.swing.JComboBox<String> transit2combobox;
    private javax.swing.JSpinner tuearrivaltimespinner;
    private javax.swing.JComboBox<String> tuecombobox;
    private javax.swing.JCheckBox tuesday;
    private javax.swing.JSpinner tuespinner;
    private javax.swing.JSpinner wedarrivaltimespinner;
    private javax.swing.JComboBox<String> wedcombobox;
    private javax.swing.JCheckBox wednesday;
    private javax.swing.JSpinner wedspinner;
    // End of variables declaration//GEN-END:variables
}
